# CRON job to fire few events like sending message notifications and deleting
# inactive users with unconfirmed email

name: Run every 5 minutes
on:
  schedule:
    - cron: "0 * * * *"
    
jobs:
  sendMessageNotification:
    runs-on: ubuntu-latest
    steps:
    - run: curl -s -X POST "https://convertx.io/api/webhook/discount-cron?token=${TOKEN}"
      env: 
        TOKEN: ${{ secrets.CRON_API_SECRET }}
